- paragraph: "\n          By LIU ZHIHUA | \n          China Daily |\n          Updated:\
    \ 2022-03-02 09:08\n        "
- paragraph: China's development offers an opportunity, and not a challenge or "threat",
    to the European Union, and the two sides share more for cooperation than competition,
    China's Commerce Minister Wang Wentao said on Tuesday.
- paragraph: Wang told a media briefing in Beijing that China is willing to join hands
    with the EU to promote the Belt and Road Initiative and align with the EU's Global
    Gateway, an infrastructure initiative announced last year, while expanding cooperation
    and deepening related mechanisms.
- paragraph: '"It is normal for the two sides to have differences and disputes due
    to different histories and cultures, social systems and development stages, but
    the two sides could strengthen communication to promote healthy competition,"
    he said, adding China and the EU are partners, not rivals.'
- paragraph: The two sides could have pragmatic cooperation in COVID-19 containment,
    green, digital, financial and technology areas among many others, and should jointly
    advance the ratification and entry into force of the EU-China Comprehensive Agreement
    on Investment, to inject more stability and positive energy for bilateral relations,
    Wang said.
- paragraph: They could step up coordination and cooperation under multilateral frameworks
    such as the G20, the United Nations, and the World Trade Organization, to promote
    the implementation of global development initiatives, maintain the multilateral
    trading system with the WTO at the core, and promote the WTO reforms toward right
    direction, he added.
- paragraph: '"We must adhere to openness and inclusiveness, abandon zero-sum mindset,
    oppose protectionism, and deepen market opening-up," Wang said.'
- paragraph: '"China and the EU could strengthen bilateral cooperation, as well as
    cooperation in the third-party markets, which will not only contribute to the
    economic development of both sides, but also the recovery and stable development
    of the world economy."'
- paragraph: Cui Fan, a professor of international trade at the University of International
    Business and Economics in Beijing, said China and the EU should enhance communication
    to remove obstacles to the implementation of their bilateral investment agreement.
- paragraph: According to Zhou Mi, a senior researcher at the Chinese Academy of International
    Trade and Economic Cooperation, China and the EU already have a solid cooperation
    base that has huge potential for growth, especially because the global supply
    chain is under disruptions and the two sides share broad common interests in multilateral
    economic and trade rules including that under the WTO.
- paragraph: '"The EU and China should take more initiatives to jointly promote pragmatic
    cooperation," Zhou said. The two sides, he said, are expected to advance long-term
    economic and trade cooperation, including mechanism-based cooperation arrangements,
    which will reduce uncertainties for enterprises seeking to grow.'
- paragraph: Based on shared interests and the world economic development trend, the
    two sides should also strengthen cooperation and coordination in new areas that
    have no widely established rules, like e-commerce and anti-trust regulation in
    the digital economy, he said.
